### ISSUE TITLE
Remove config files from git

### ISSUE THREAD

**Issue by jakubzitny** [Mondego/SourcererCC#10]
As an improvement I'd suggest removing the config files from the repository. I am not sure how you guys work with git, but usually you only submit a sample config and each contributor/user then copies the file to correct location and changes its contensts. This way no useless unstaged changes will be shown in git.

I'd also add all "standard" output locations to `.gitignore`.

For this project the config files would be at least
- `clone-detector/sourcerer-cc.properties`
- `tokenizers/file-level/config.ini`

And the locations for ignore would be
- *.log
- clone-detector/dist/
- clone-detector/fwdindex/
- clone-detector/index/
- clone-detector/gtpm/
- tokenizers/file-level/bookkeeping_files/
- tokenizers/file-level/bookkeeping_projs/
- tokenizers/file-level/projects_success.txt
- tokenizers/file-level/project_starting_index.txt
- tokenizers/file-level/projects_fail.txt
- tokenizers/file-level/mirror_repo
- tokenizers/file-level/tokens
- tokenizers/file-level/project-list.txt

**Comment by jakubzitny** [comment]
I am suggesting the gitignores like this: https://github.com/jakubzitny/SourcererCC/commit/c5bc0f8340761b3c09ca7c030254514b16239156 and https://github.com/jakubzitny/SourcererCC/commit/9b581f6fc0ef5a1d14caddcd466f1cfa0d343abc.

**Comment by pedromartins4** [comment]
Thanks for your note @jakubzitny . We're looking into it.
