### ISSUE TITLE
Question on <parentId, blockId> 

### ISSUE THREAD

**Issue by rajbarik** [Mondego/SourcererCC#16]
The source code [not the pre-built jar file] seem to expect a tuple with three fields as opposed to two mentioned in the doc <parentId, blockId>. What is the third argument? Can someone clarify? Or is this a recent bug?

String[] bagAndTokens = s.split("@#@");
                String[] bagMetadata = bagAndTokens[0].split(",");
                String functionId = bagMetadata[0];
                String bagId = bagMetadata[1];
                int bagSize = Integer.parseInt(bagMetadata[2]);

**Comment by saini** [comment]
The third argument is the total number of tokens in the block. 
We decided that the metadata about the block of code should also be present in the input file. This allows us to do speed up the performance of SCC.

**Comment by rajbarik** [comment]
Thanks. But when I run "ant cdini; ./run.sh" I get the following class not found error. Why? The jar file does not seem to contain the other jars from lib. With jar, the -cp option does not work. How do I get this to work? I do have a token file named input/dataset/codeclonedetection-clone-INPUT.txt.

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
	at com.mondego.noindex.CloneDetectorWithFilter.main(CloneDetectorWithFilter.java:140)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonSyntaxException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

**Comment by rajbarik** [comment]
I have created a tokens file in correct format, I believe and I am struggling to get the whole thing running on a laptop. Can you point me to a simple script that I can pass my tokens file and get all the clones detected? runnodes.sh seem to target multiple nodes and crashes when I run my file. Although this command "java -Xms4g -Xmx4g -cp "dist/noindex.CloneDetector.jar:lib/*" com.mondego.noindex.CloneDetector clonedetection 8 overlap" runs fine, where does the clone pairs reported? I can not locate them. 
Essentially, I am looking for a simple single node script to run the clone detector that outputs all the clones. Which script does that?

**Comment by pedromartins4** [comment]
Since this was more than a month ago I am closing it.
