### ISSUE TITLE
Why I failed when executing "python controller.py"

### ISSUE THREAD

**Issue by Kaka727** [Mondego/SourcererCC#26]
I try to reproduce the experiments using the original materials.
Everything goes well before I executed "python controller.py"
![image](https://user-images.githubusercontent.com/33283686/50137419-0f08c280-02d6-11e9-9508-492a29845306.png)
How can I solve this problem?
Is it correlated with my python version or something else?

**Comment by saini** [comment]
Could you please upload the files which start with “Log_”. Please zip all such files together and upload them here. Also, there should be a folder SCC_logs, please zip it and upload it here.

**Comment by Kaka727** [comment]
@saini 
I find this file may be useful for this problem
Is it an out of memory error?
[hs_err_pid17609.log](https://github.com/Mondego/SourcererCC/files/2689373/hs_err_pid17609.log)

**Comment by saini** [comment]
Yes, it is an Out of Memory error.  Please make sure you have enough Ram before you run SourcererCC. You may set heap size for JVM in the runnodes.sh file (you can set the XMX and XMS parameters here: https://github.com/Mondego/SourcererCC/blob/master/clone-detector/runnodes.sh#L22). 
Also, when instead of running `python controller.py`, please run `python controller.py 1`

**Comment by Kaka727** [comment]
@saini Yeah, thanks a lot. I have successfully run the examples of file_level.
Another question occurs that this tool can detect clones at file, method, block levels. But I do not know how to conduct experiment at the other two levels. Maybe block level can be executed similar to the exampled file level, but in the folder "tokenizer", there is no file named "method". So I would appreciate it if you teach me how to do it.

**Comment by saini** [comment]
Hi @Kaka727, I let me connect you to @pedromartins4  and @dyangUCI. They have more idea about the tokenizer code. They should be able to help you. Also, I request you to create a new issue threads to discuss different issues. 
Thanks for your interest in SourcererCC

**Comment by dyangUCI** [comment]
Hi @Kaka727 , I didn't see "zipblocks" in your commands. Could you try "python tokenizer.py zipblocks" if your projects are zipped or "python tokenizer.py folderblocks" if your projects are under folders?

**Comment by vikasuhag** [comment]
> 
> 
> @saini Yeah, thanks a lot. I have successfully run the examples of file_level.
> Another question occurs that this tool can detect clones at file, method, block levels. But I do not know how to conduct experiment at the other two levels. Maybe block level can be executed similar to the exampled file level, but in the folder "tokenizer", there is no file named "method". So I would appreciate it if you teach me how to do it.

I am 

> 
> 
> Yes, it is an Out of Memory error. Please make sure you have enough Ram before you run SourcererCC. You may set heap size for JVM in the runnodes.sh file (you can set the Xmx and Xms parameters here: https://github.com/Mondego/SourcererCC/blob/master/clone-detector/runnodes.sh#L22).
> Also, instead of running `python controller.py`, please run `python controller.py 1`

I am facing the same issue, could you please help me, what is the minimum ram required for system, I am running it on windows 10, first process of tokenizing was done.
