### ISSUE TITLE
SourcererCC used old library of eproperties

### ISSUE THREAD

**Issue by vizigin** [Mondego/SourcererCC#37]
Hi, guys

We tried to apply SourcererCC to our deployment infrastructure, but It have old library, which not supported by java 8 update 201. I look [here](https://code.google.com/archive/p/eproperties/downloads) and It's looks like dead (last update May 15, 2012). Have you plan to fixes for SourcererCC?

**Comment by vizigin** [comment]
I get warnings like that:
<img width="750" alt="clone-detector — -bash — 107×37 2019-04-16 20-58-46" src="https://user-images.githubusercontent.com/1876640/56220596-84b94b00-608a-11e9-89af-3bbabfe08cb2.png">

**Comment by vizigin** [comment]
I add this 
<img width="660" alt="1_1" src="https://user-images.githubusercontent.com/1876640/56221244-b979d200-608b-11e9-849a-dcd2f2e33053.png">

to the code and get this in logs:
<img width="893" alt="1_2" src="https://user-images.githubusercontent.com/1876640/56221252-be3e8600-608b-11e9-8a67-04535bc50880.png">

**Comment by saini** [comment]
Thanks for reporting this. I will look into it. I can not commit on ETA, but expect a delay of 1-2 days. 
Apologies for the inconvenience.

**Comment by vizigin** [comment]
[Here](https://github.com/vizigin/SourcererCC/commit/f8c0fc58ac77bfe72db3bc5b9ba04692b6ba5398) I reverted to native java library. I can make pull request

**Comment by saini** [comment]
sure, please go ahead and I'll approve it after reviewing the changes. 
Thanks

**Comment by vizigin** [comment]
It's [here](https://github.com/Mondego/SourcererCC/pull/38)
