### ISSUE TITLE
Is the bookkeeping file used by SourcererCC?

### ISSUE THREAD

**Issue by jakubzitny** [Mondego/SourcererCC#5]
Hi, the `Readme` is not clear about where to put the bookkeeping `headers.file`.

Does SourcererCC actually use this file or is it just for manual check of the block/file that is found?

**Comment by saini** [comment]
headers.file is not directly used by SourcererCC. It is used for post processing purpose, especially to track the code-block ids to their code snippets. 
Going further, we need to figure out a good home for it. Currently, we make a bookkeepings folder inside the input folder and then drop this file there. 

```SourcererCC`
|--input
    | -- bookkeepings
          |-- headers.file
```

**Comment by saini** [comment]
No, SourcererCC (SCC) doesn't use bookkeeping file. However, it can be used outside of SCC if you want to look into the body of clone pairs.

**Comment by saini** [comment]
closing this.
