### ISSUE TITLE
Provide the patch which makes the block-level tokenizer.py compatible with current python version  

### ISSUE THREAD

**Issue by zzc1010** [Mondego/SourcererCC#51]
[diff.txt](https://github.com/Mondego/SourcererCC/files/8323979/diff.txt)

**Comment by Rexime** [comment]
> 
hi, I'm learning how to use SourcererCC, and when I try to use tokenizer as written in Readme, I failed. all the output files are empty, can you help me?

**Comment by zzc1010** [comment]
您好，您的邮件我已收到，祝天天开心。

**Comment by crista** [comment]
Thanks. I merged it. Almost all, but not all.
https://github.com/Mondego/SourcererCC/commit/c296871e3315533563e3060476f45ed5cbfbd083

**Comment by zzc1010** [comment]
您好，您的邮件我已收到，祝天天开心。
